# Generated by Django 5.2 on 2025-05-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='learning_items/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quizzes/'),
        ),
    ]
